### PR TITLE
APIHandler Refactoring

### PR DESCRIPTION
**Pull request by burrscurr**
This pull request is about refactoring `APIHandler.py` as proposed in #9. The file is much smaller now.

My changes are yet untested, since I will probably just get hands on a reolink camera in the next days.

### CODE REVIEW

**Comment by burrscurr** [comment]
One could also split the `APIHandler.py` fie into single mixins, which would help to keep the files readable and make it easier to find single calls. A possible split would be into the main file / user / system / network / zoom+focus.

**Comment by Benehiko** [comment]
That could work, you can add it to this PR and I will do the merge when you're ready.

**Comment by burrscurr** [comment]
I have tested my changes with a RLC-411. Some calls could not be tested, because my camera does not support the actions: 
- `get_hdd`, `format_hdd`

My last commit definitely changes behaviour. At least for my camera, some return value checks had to be changed. If that is unwanted or even incorrect with other behaviour, the last commit may be reverted.

**Comment by Benehiko** [comment]
No problem ! 
great work :+1:

**Pull request merged**
